services:
  klog-dashboard:
    image: ghcr.io/muecahit94/klog-dashboard:latest
    build: .
    container_name: klog-dashboard
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - KLOG_DATA_DIR=/data
    volumes:
      - /Users/muecahit/Dropbox/Allgemeines/Arbeitsunterlagen/Whizus/timetracking:/data
    labels:
      - "com.docker.compose.project=klog-dashboard"
